name: Daily Commit Workflow

on:
  schedule:
    # Runs at 10:30 UTC every day
    - cron: '30 10 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  daily-commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git - 23f2005607@ds.study.iitm.ac.in
      run: |
        git config --local user.email "23f2005607@ds.study.iitm.ac.in"
        git config --local user.name "GitHub Action Bot"
    
    - name: Create daily update
      run: |
        # Create or update a daily log file
        mkdir -p logs
        echo "Daily update: $(date)" >> logs/daily-updates.log
        echo "Workflow run at: $(date -u)" >> logs/daily-updates.log
        echo "---" >> logs/daily-updates.log
    
    - name: Commit changes
      run: |
        git add .
        git commit -m "Daily automated commit - $(date -u)"
        git push 